services:
  web:
    image: ${DOCKERHUB_USERNAME}/web:latest

  scheduler:
    image: ${DOCKERHUB_USERNAME}/scheduler:latest

  worker:
    image: ${DOCKERHUB_USERNAME}/worker:latest

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"