services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-net
    environment:
      MONGO_URI: "mongodb://mongo:27017/"
      DB_NAME: "mydb"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-net
    env_file:
      - .env

  scheduler:
    build: ./scheduler
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-net
    env_file:
      - .env

  worker:
    build: ./worker
    depends_on:
      - mongo
      - rabbitmq
      - scheduler
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://mongo:27017/"
      DB_NAME: "mydb"


volumes:
  mongo-data:

networks:
  app-net:
